
Revision ID: 555b985de228
Revises:
Create Date: 2026-08-18 08:12:02.631666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '555b985de228'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definitions_formulaire',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('parametres',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cle', sa.String(length=100), nullable=False),
    sa.Column('valeur', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('string', 'int', 'decimal', 'bool', name='type_parametre_enum'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('modifiable_par', sa.String(length=50), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cle')
    )
    op.create_table('pays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_iso', sa.String(length=3), nullable=False),
    sa.Column('code_numerique', sa.String(length=2), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('ordre_alpha', sa.Integer(), nullable=False),
    sa.Column('version_linguistique_defaut', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_iso'),
    sa.UniqueConstraint('code_numerique')
    )
    op.create_table('compteurs_numerotation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pays_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.String(length=4), nullable=False),
    sa.Column('dernier_numero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pays_id'], ['pays.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pays_id', 'annee', name='uq_compteur_pays_annee')
    )
    op.create_table('definitions_champ',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('formulaire_id', sa.String(length=36), nullable=False),
    sa.Column('code_champ', sa.String(length=100), nullable=False),
    sa.Column('libelle_fr', sa.String(length=255), nullable=False),
    sa.Column('libelle_en', sa.String(length=255), nullable=True),
    sa.Column('libelle_ar', sa.String(length=255), nullable=True),
    sa.Column('type_champ', sa.Enum('texte', 'nombre', 'date', 'liste', 'booleen', name='type_champ_enum'), nullable=False),
    sa.Column('obligatoire', sa.Boolean(), nullable=False),
    sa.Column('ordre_affichage', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('regle_validation', sa.String(length=500), nullable=True),
    sa.Column('options_liste', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formulaire_id'], ['definitions_formulaire.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formulaire_id', 'code_champ', name='uq_definitions_champ_formulaire_code')
    )
    op.create_table('postes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('pays_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pays_id'], ['pays.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hash_mdp', sa.String(length=255), nullable=False),
    sa.Column('nom_complet', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin_national', 'agent_emission', 'agent_controle', 'veterinaire', 'consultation', name='role_enum'), nullable=False),
    sa.Column('pays_id', sa.Integer(), nullable=True),
    sa.Column('poste_id', sa.String(length=36), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pays_id'], ['pays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('autorisations_impression',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pays_id', sa.Integer(), nullable=False),
    sa.Column('plage_debut', sa.Integer(), nullable=False),
    sa.Column('plage_fin', sa.Integer(), nullable=False),
    sa.Column('gabarit_version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('suspendue_par_id', sa.String(length=36), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pays_id'], ['pays.id'], ),
    sa.ForeignKeyConstraint(['suspendue_par_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commandes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pays_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('langue_version', sa.Enum('FR/EN', 'FR/AR', name='version_ling_enum'), nullable=False),
    sa.Column('mode_impression', sa.Enum('centralisee', 'decentralisee', name='mode_impr_enum'), nullable=False),
    sa.Column('montant_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('statut', sa.Enum('brouillon', 'en_attente_paiement', 'payee', 'expiree', 'annulee', name='statut_commande_enum'), nullable=False),
    sa.Column('responsable_nom', sa.String(length=255), nullable=False),
    sa.Column('cree_par_id', sa.String(length=36), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['pays_id'], ['pays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piste_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entite', sa.String(length=100), nullable=False),
    sa.Column('entite_id', sa.String(length=100), nullable=False),
    sa.Column('ancienne_valeur', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('nouvelle_valeur', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('textes_gabarit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gabarit_version', sa.Integer(), nullable=False),
    sa.Column('cle', sa.String(length=100), nullable=False),
    sa.Column('langue', sa.String(length=5), nullable=False),
    sa.Column('valeur', sa.String(length=2000), nullable=False),
    sa.Column('statut', sa.Enum('propose', 'valide', 'rejete', name='statut_texte_gabarit_enum'), nullable=False),
    sa.Column('propose_par_id', sa.String(length=36), nullable=False),
    sa.Column('valide_par_id', sa.String(length=36), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['propose_par_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['valide_par_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('commande_id', sa.String(length=36), nullable=False),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('devise', sa.String(length=3), nullable=False),
    sa.Column('moyen', sa.Enum('mobile_money', 'carte_bancaire', 'virement', 'especes', 'cheque', name='moyen_paiement_enum'), nullable=False),
    sa.Column('statut', sa.Enum('initie', 'en_attente_validation', 'valide', 'echoue', 'rembourse', name='statut_paiement_enum'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('valide_par_id', sa.String(length=36), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['valide_par_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('passeports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('commande_id', sa.String(length=36), nullable=False),
    sa.Column('pays_id', sa.Integer(), nullable=False),
    sa.Column('numero_pays', sa.String(length=2), nullable=False),
    sa.Column('numero_annee', sa.String(length=4), nullable=False),
    sa.Column('numero_lot', sa.String(length=7), nullable=False),
    sa.Column('qr_uuid', sa.String(length=36), nullable=False),
    sa.Column('code_verification', sa.String(length=10), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=512), nullable=False),
    sa.Column('gabarit_version', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('precharge', 'vierge', 'emis', 'controle', 'revoque', name='statut_passeport_enum'), nullable=False),
    sa.Column('publie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['pays_id'], ['pays.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pays_id', 'numero_annee', 'numero_lot', name='uq_passeport_pays_annee_lot'),
    sa.UniqueConstraint('qr_uuid')
    )
    op.create_table('controles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('passeport_id', sa.String(length=36), nullable=False),
    sa.Column('poste_id', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('resultat', sa.Enum('valide', 'refuse', 'a_verifier', name='resultat_controle_enum'), nullable=False),
    sa.Column('itineraire_disponible_localement', sa.Boolean(), nullable=False),
    sa.Column('conforme_itineraire', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.Enum('en_ligne', 'hors_ligne', name='mode_verif_enum'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['passeport_id'], ['passeports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convoyeurs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('passeport_id', sa.String(length=36), nullable=False),
    sa.Column('nom_prenom', sa.String(length=255), nullable=False),
    sa.Column('numero_cni', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('donnees_dynamiques', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('date_enregistrement', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passeport_id'], ['passeports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passeport_id')
    )
    op.create_table('eleveurs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('passeport_id', sa.String(length=36), nullable=False),
    sa.Column('nom_prenom', sa.String(length=255), nullable=False),
    sa.Column('numero_cni', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('donnees_dynamiques', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('date_enregistrement', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passeport_id'], ['passeports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passeport_id')
    )
    op.create_table('itineraires',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('passeport_id', sa.String(length=36), nullable=False),
    sa.Column('pays_origine_id', sa.Integer(), nullable=False),
    sa.Column('province_origine', sa.String(length=255), nullable=False),
    sa.Column('localite_origine', sa.String(length=255), nullable=True),
    sa.Column('pays_destination_id', sa.Integer(), nullable=False),
    sa.Column('province_destination', sa.String(length=255), nullable=False),
    sa.Column('localite_destination', sa.String(length=255), nullable=True),
    sa.Column('date_enregistrement', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('synchronise_vers_controle', sa.Boolean(), nullable=False),
    sa.Column('publie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passeport_id'], ['passeports.id'], ),
    sa.ForeignKeyConstraint(['pays_destination_id'], ['pays.id'], ),
    sa.ForeignKeyConstraint(['pays_origine_id'], ['pays.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passeport_id')
    )
    op.create_table('numerisations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('passeport_id', sa.String(length=36), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=False),
    sa.Column('donnees_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('statut_validation', sa.Enum('en_attente', 'validee', name='statut_validation_enum'), nullable=False),
    sa.Column('statut_sync', sa.Enum('local', 'synchronisee', name='statut_sync_enum'), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['passeport_id'], ['passeports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passeport_id', 'page_num', name='uq_numerisation_passeport_page')
    )
    op.create_table('troupeaux',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('passeport_id', sa.String(length=36), nullable=False),
    sa.Column('date_enregistrement', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passeport_id'], ['passeports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passeport_id')
    )
    op.create_table('troupeau_especes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('troupeau_id', sa.String(length=36), nullable=False),
    sa.Column('espece', sa.String(length=50), nullable=False),
    sa.Column('nombre_males', sa.Integer(), nullable=False),
    sa.Column('nombre_femelles_jeunes', sa.Integer(), nullable=False),
    sa.Column('nombre_femelles_adultes', sa.Integer(), nullable=False),
    sa.Column('nombre_total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['troupeau_id'], ['troupeaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccinations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('troupeau_id', sa.String(length=36), nullable=False),
    sa.Column('maladie', sa.String(length=100), nullable=False),
    sa.Column('date_vaccination', sa.Date(), nullable=True),
    sa.Column('lieu', sa.String(length=255), nullable=True),
    sa.Column('valide_par_veterinaire_id', sa.String(length=36), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['troupeau_id'], ['troupeaux.id'], ),
    sa.ForeignKeyConstraint(['valide_par_veterinaire_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccinations')
    op.drop_table('troupeau_especes')
    op.drop_table('troupeaux')
    op.drop_table('numerisations')
    op.drop_table('itineraires')
    op.drop_table('eleveurs')
    op.drop_table('convoyeurs')
    op.drop_table('controles')
    op.drop_table('passeports')
    op.drop_table('paiements')
    op.drop_table('textes_gabarit')
    op.drop_table('piste_audit')
    op.drop_table('commandes')
    op.drop_table('autorisations_impression')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_table('postes')
    op.drop_table('definitions_champ')
    op.drop_table('compteurs_numerotation')
    op.drop_table('pays')
    op.drop_table('parametres')
    op.drop_table('definitions_formulaire')
    # ### end Alembic commands ###