"""table photos_ocr

Revision ID: 7ce067743de6
Revises: 555b985de228
Create Date: 2026-08-18 16:16:30.198064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7ce067743de6'
down_revision: Union[str, None] = '555b985de228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos_ocr',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('passeport_id', sa.String(length=36), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=False),
    sa.Column('image_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('image_content_type', sa.String(length=50), nullable=False),
    sa.Column('resultat_ocr_brut', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['passeport_id'], ['passeports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos_ocr')
    # ### end Alembic commands ###