"""table branding

Revision ID: 9041ebe84083
Revises: 7ce067743de6
Create Date: 2026-08-20 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '9041ebe84083'
down_revision: Union[str, None] = '7ce067743de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('nom_application', sa.String(length=100), nullable=False),
    sa.Column('couleur_primaire', sa.String(length=7), nullable=False),
    sa.Column('couleur_primaire_claire', sa.String(length=7), nullable=False),
    sa.Column('logo_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('logo_content_type', sa.String(length=50), nullable=True),
    sa.Column('icone_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('icone_content_type', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branding')
    # ### end Alembic commands ###
